import { CardData } from "./Interface";

export const data: CardData[] = [
  {
    id: '1',
    title: "Xiaomi Redmi Note 11",
    urlToImg: "../src/assets/phones/5.png",
    amount: 4,
    year: 2012,
    manufacturer: "Xiaomi",
    color: "белый",
    cameras: 1,
    isPopular: "да",
  },
  {
    id: '2',
    title: "Xiaomi Redmi 9C 3/64gb",
    urlToImg: "../src/assets/phones/6.png",
    amount: 6,
    year: 2010,
    manufacturer: "Xiaomi",
    color: "красный",
    cameras: 2,
    isPopular: "нет",
  },
  {
    id: '3',
    title: "Xiaomi Poco X4 pro1",
    urlToImg: "../src/assets/phones/4.png",
    amount: 1,
    year: 2014,
    manufacturer: "Xiaomi",
    color: "желтый",
    cameras: 2,
    isPopular: "нет",
  },
  {
    id: '4',
    title: "Samsung Galaxy S21",
    urlToImg: "../src/assets/phones/1.png",
    amount: 2,
    year: 2019,
    manufacturer: "Samsung",
    color: "белый",
    cameras: 3,
    isPopular: "нет",
  },
  {
    id: '5',
    title: "Samsung Galaxy S20",
    urlToImg: "../src/assets/phones/3.png",
    amount: 3,
    year: 2022,
    manufacturer: "Samsung",
    color: "желтый",
    cameras: 1,
    isPopular: "нет",
  },
  {
    id: '6',
    title: "Samsung Galaxy A03",
    urlToImg: "../src/assets/phones/2.png",
    amount: 5,
    year: 2000,
    manufacturer: "Samsung",
    color: "красный",
    cameras: 2,
    isPopular: "нет",
  },
  {
    id: '7',
    title: "Apple iPhone SE",
    urlToImg: "../src/assets/phones/10.png",
    amount: 7,
    year: 2004,
    manufacturer: "Apple",
    color: "белый",
    cameras: 1,
    isPopular: "нет",
  },
  {
    id: '8',
    title: "Apple iPhone 13",
    urlToImg: "../src/assets/phones/8.png",
    amount: 10,
    year: 2009,
    manufacturer: "Apple",
    color: "красный",
    cameras: 3,
    isPopular: "нет",
  },
  {
    id: '9',
    title: "Apple iPhone 12",
    urlToImg: "../src/assets/phones/9.png",
    amount: 2,
    year: 2010,
    manufacturer: "Apple",
    color: "желтый",
    cameras: 3,
    isPopular: "нет",
  },
  {
    id: '10',
    title: "Apple iPhone 11",
    urlToImg: "../src/assets/phones/7.png",
    amount: 12,
    year: 2018,
    manufacturer: "Apple",
    color: "белый",
    cameras: 3,
    isPopular: "да",
  },
];