import { CardData } from './Interface';

export const data: CardData[] = [
  {
    id: '1',
    title: 'Xiaomi Redmi Note 11',
    urlToImg: '../src/assets/phones/5.png',
    amount: 4,
    year: 2012,
    manufacturer: 'Xiaomi',
    color: 'белый',
    cameras: 1,
    isPopular: 'да',
  },
  {
    id: '2',
    title: 'Xiaomi Redmi 9C 3/64gb',
    urlToImg: '../src/assets/phones/6.png',
    amount: 6,
    year: 2010,
    manufacturer: 'Xiaomi',
    color: 'красный',
    cameras: 2,
    isPopular: 'нет',
  },
  {
    id: '3',
    title: 'Xiaomi Poco X4 pro1',
    urlToImg: '../src/assets/phones/4.png',
    amount: 1,
    year: 2014,
    manufacturer: 'Xiaomi',
    color: 'желтый',
    cameras: 2,
    isPopular: 'нет',
  },
  {
    id: '4',
    title: 'Samsung Galaxy S21',
    urlToImg: '../src/assets/phones/1.png',
    amount: 2,
    year: 2019,
    manufacturer: 'Samsung',
    color: 'белый',
    cameras: 3,
    isPopular: 'нет',
  },
  {
    id: '5',
    title: 'Samsung Galaxy S20',
    urlToImg: '../src/assets/phones/3.png',
    amount: 3,
    year: 2022,
    manufacturer: 'Samsung',
    color: 'желтый',
    cameras: 1,
    isPopular: 'нет',
  },
  {
    id: '6',
    title: 'Samsung Galaxy A03',
    urlToImg: '../src/assets/phones/2.png',
    amount: 5,
    year: 2000,
    manufacturer: 'Samsung',
    color: 'красный',
    cameras: 2,
    isPopular: 'нет',
  },
  {
    id: '7',
    title: 'Apple iPhone SE',
    urlToImg: '../src/assets/phones/10.png',
    amount: 7,
    year: 2004,
    manufacturer: 'Apple',
    color: 'белый',
    cameras: 1,
    isPopular: 'нет',
  },
  {
    id: '8',
    title: 'Apple iPhone 13',
    urlToImg: '../src/assets/phones/8.png',
    amount: 10,
    year: 2009,
    manufacturer: 'Apple',
    color: 'красный',
    cameras: 3,
    isPopular: 'нет',
  },
  {
    id: '9',
    title: 'Apple iPhone 12',
    urlToImg: '../src/assets/phones/9.png',
    amount: 2,
    year: 2010,
    manufacturer: 'Apple',
    color: 'желтый',
    cameras: 3,
    isPopular: 'нет',
  },
  {
    id: '10',
    title: 'Apple iPhone 11',
    urlToImg: '../src/assets/phones/7.png',
    amount: 12,
    year: 2018,
    manufacturer: 'Apple',
    color: 'белый',
    cameras: 3,
    isPopular: 'да',
  },
  {
    id: '11',
    title: 'Apple iPhone 13',
    urlToImg: '../src/assets/phones/11.png',
    amount: 10,
    year: 2021,
    manufacturer: 'Apple',
    color: 'белый',
    cameras: 3,
    isPopular: 'да',
  },
  {
    id: '12',
    title: 'Apple iPhone 12 mini',
    urlToImg: '../src/assets/phones/12.png',
    amount: 1,
    year: 2020,
    manufacturer: 'Apple',
    color: 'белый',
    cameras: 3,
    isPopular: 'нет',
  },
  {
    id: '13',
    title: 'Apple iPhone 13 Pro Max',
    urlToImg: '../src/assets/phones/13.png',
    amount: 7,
    year: 2021,
    manufacturer: 'Apple',
    color: 'желтый',
    cameras: 4,
    isPopular: 'нет',
  },
  {
    id: '14',
    title: 'Apple iPhone XS',
    urlToImg: '../src/assets/phones/14.png',
    amount: 7,
    year: 2020,
    manufacturer: 'Apple',
    color: 'желтый',
    cameras: 3,
    isPopular: 'да',
  },
  {
    id: '15',
    title: 'Xiaomi 12 Lite',
    urlToImg: '../src/assets/phones/15.png',
    amount: 2,
    year: 2022,
    manufacturer: 'Xiaomi',
    color: 'красный',
    cameras: 4,
    isPopular: 'нет',
  },
  {
    id: '16',
    title: 'Xiaomi Redmi 10',
    urlToImg: '../src/assets/phones/16.png',
    amount: 4,
    year: 2022,
    manufacturer: 'Xiaomi',
    color: 'белый',
    cameras: 5,
    isPopular: 'да',
  },
  {
    id: '17',
    title: 'Xiaomi 11 Lite',
    urlToImg: '../src/assets/phones/17.png',
    amount: 6,
    year: 2021,
    manufacturer: 'Xiaomi',
    color: 'красный',
    cameras: 4,
    isPopular: 'нет',
  },
  {
    id: '18',
    title: 'Samsung Galaxy S22+',
    urlToImg: '../src/assets/phones/18.png',
    amount: 20,
    year: 2022,
    manufacturer: 'Samsung',
    color: 'белый',
    cameras: 4,
    isPopular: 'нет',
  },
  {
    id: '19',
    title: 'Samsung Galaxy A33',
    urlToImg: '../src/assets/phones/19.png',
    amount: 17,
    year: 2022,
    manufacturer: 'Samsung',
    color: 'желтый',
    cameras: 5,
    isPopular: 'да',
  },
  {
    id: '20',
    title: 'Samsung Galaxy S22',
    urlToImg: '../src/assets/phones/20.png',
    amount: 3,
    year: 2022,
    manufacturer: 'Samsung',
    color: 'красный',
    cameras: 4,
    isPopular: 'нет',
  },
  {
    id: '21',
    title: 'Samsung Galaxy S22 Ultra',
    urlToImg: '../src/assets/phones/21.png',
    amount: 3,
    year: 2022,
    manufacturer: 'Samsung',
    color: 'белый',
    cameras: 5,
    isPopular: 'нет',
  },
  {
    id: '22',
    title: 'Realme 9i',
    urlToImg: '../src/assets/phones/22.png',
    amount: 9,
    year: 2022,
    manufacturer: 'Realme',
    color: 'синий',
    cameras: 4,
    isPopular: 'да',
  },
  {
    id: '23',
    title: 'Realme 8i',
    urlToImg: '../src/assets/phones/23.png',
    amount: 2,
    year: 2021,
    manufacturer: 'Realme',
    color: 'черный',
    cameras: 4,
    isPopular: 'нет',
  },
  {
    id: '24',
    title: 'Realme C25s',
    urlToImg: '../src/assets/phones/24.png',
    amount: 14,
    year: 2021,
    manufacturer: 'Realme',
    color: 'синий',
    cameras: 4,
    isPopular: 'нет',
  },
  {
    id: '25',
    title: 'Realme 9 Pro',
    urlToImg: '../src/assets/phones/25.png',
    amount: 18,
    year: 2022,
    manufacturer: 'Realme',
    color: 'черный',
    cameras: 4,
    isPopular: 'нет',
  },
];
